# Change these first
owner: XzFrosT # Your GitHub username
repo: uptime-XzF # Your GitHub repository name

# Add your sites here
sites:
  - name: Shiro Neko
    url: https://shiro-nekoo.glitch.me
    icon: https://harmonymusic.tk/assets/img/logo.png
  - name: Brain Bot Discord 
    url: https://brain-bot-discord.xzfrostt.repl.co
    icon: https://i.imgur.com/jIqqUie.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptimer
  logoUrl: https://harmonymusic.tk/assets/img/logo.png
  name: Uptime XzFrosT
  introTitle: "This is an uptime website for my discord bot"
  introMessage: This Website is owned by [XzFrosT](https://youtube.com/XzFrosT)
  navbar:
    - title: Home
      href: /
    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
