# Change these first
owner: XzFrosT # Your GitHub username
repo: uptime-XzF # Your GitHub repository name

# Add your sites here
sites:
  - name: Uptimer 
    url: https://brain-bott.glitch.me
    icon: https://harmonymusic.tk/assets/img/logo.png
  



status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime-XzF 
  logoUrl: https://harmonymusic.tk/assets/img/logo.png
  name: Uptime XzFrosT
  introTitle: "This is an uptime website for Uptime XzFrosT websites!"
  introMessage: This Website is owned by [XzFrosT](https://youtube.com/XzFrosT)
  navbar:
    - title: Home
      href: /
    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
